# PANDAS PRACTISE

In [15]:
pip install pandas

Requirement already satisfied: pandas in c:\users\dharm\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dharm\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dharm\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dharm\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dharm\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\dharm\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [16]:
import pandas as pd

In [17]:
data = {
    "name":["Sumit","Rahul","Ankit"],
    "age":[25,30,35]
}
df = pd.DataFrame(data)

In [13]:
print(df)

    name  age
0  Sumit   25
1  Rahul   30
2  Ankit   35

In [18]:
df["Salary"] = [25000,30000,35000]

In [19]:
df

    name  age  Salary
0  Sumit   25   25000
1  Rahul   30   30000
2  Ankit   35   35000

In [227]:
df = pd.read_csv('orders.csv')
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [19]:
df.head()  # head() show only top 5 rows

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5

In [20]:
df.head(10)

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5

In [21]:
df.dtypes # .dtypes tells datatype of each columns

order_id        object
order_date      object
ship_date       object
ship_mode       object
customer_id     object
region          object
product_id      object
category        object
sales          float64
quantity         int64
profit         float64
dtype: object

In [23]:
df.info() # .info() tells more about dataframes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     50 non-null     object
 1   order_date   50 non-null     object
 2   ship_date    50 non-null     object
 3   ship_mode    50 non-null     object
 4   customer_id  50 non-null     object
 5   region       50 non-null     object
 6   product_id   50 non-null     object
 7   category     50 non-null     object
 8   sales        50 non-null     float64
 9   quantity     50 non-null     int64
 10  profit       50 non-null     float64
dtypes: float64(2), int64(1), object(8)
memory usage: 4.4+ KB

In [24]:
df.describe()

             sales   quantity       profit
count    50.000000  50.000000    50.000000
mean    300.792000   3.920000   -20.550000
std     547.564035   1.977836   251.767027
min       2.500000   2.000000 -1665.100000
25%      20.075000   2.000000     2.500000
50%      74.650000   3.000000     8.350000
75%     249.875000   5.000000    17.650000
max    3083.400000   9.000000   240.300000

In [7]:
df.columns

Index(['name', 'age'], dtype='object')

In [25]:
col = ['order_id','order_date','ship_date'] # by this you can select only particular column
df[col]

          order_id  order_date   ship_date
0   CA-2020-152156  08-11-2020  11-11-2020
1   CA-2020-152156  08-11-2020  11-11-2020
2   CA-2020-138688  12-06-2020  16-06-2020
3   US-2019-108966  11-10-2019  18-10-2019
4   US-2019-108966  11-10-2019  18-10-2019
5   CA-2018-115812  09-06-2018  14-06-2018
6   CA-2018-115812  09-06-2018  14-06-2018
7   CA-2018-115812  09-06-2018  14-06-2018
8   CA-2018-115812  09-06-2018  14-06-2018
9   CA-2018-115812  09-06-2018  14-06-2018
10  CA-2018-115812  09-06-2018  14-06-2018
11  CA-2018-115812  09-06-2018  14-06-2018
12  CA-2021-114412  15-04-2021  20-04-2021
13  CA-2020-161389  05-12-2020  10-12-2020
14  US-2019-118983  22-11-2019  26-11-2019
15  US-2019-118983  22-11-2019  26-11-2019
16  CA-2018-105893  11-11-2018  18-11-2018
17  CA-2018-167164  13-05-2018  15-05-2018
18  CA-2018-143336  27-08-2018  01-09-2018
19  CA-2018-143336  27-08-2018  01-09-2018
20  CA-2018-143336  27-08-2018  01-09-2018
21  CA-2020-137330  09-12-2020  13-12-2020
22  CA-2020-137330  09-12-2020  13-12-2020
23  US-2021-156909  16-07-2021  18-07-2021
24  CA-2019-106320  25-09-2019  30-09-2019
25  CA-2020-121755  16-01-2020  20-01-2020
26  CA-2020-121755  16-01-2020  20-01-2020
27  US-2019-150630  17-09-2019  21-09-2019
28  US-2019-150630  17-09-2019  21-09-2019
29  US-2019-150630  17-09-2019  21-09-2019
30  US-2019-150630  17-09-2019  21-09-2019
31  US-2019-150630  17-09-2019  21-09-2019
32  US-2019-150630  17-09-2019  21-09-2019
33  US-2019-150630  17-09-2019  21-09-2019
34  CA-2021-107727  19-10-2021  23-10-2021
35  CA-2020-117590  08-12-2020  10-12-2020
36  CA-2020-117590  08-12-2020  10-12-2020
37  CA-2019-117415  27-12-2019  31-12-2019
38  CA-2019-117415  27-12-2019  31-12-2019
39  CA-2019-117415  27-12-2019  31-12-2019
40  CA-2019-117415  27-12-2019  31-12-2019
41  CA-2021-120999  10-09-2021  15-09-2021
42  CA-2020-101343  17-07-2020  22-07-2020
43  CA-2021-139619  19-09-2021  23-09-2021
44  CA-2020-118255  11-03-2020  13-03-2020
45  CA-2020-118255  11-03-2020  13-03-2020
46  CA-2018-146703  20-10-2018  25-10-2018
47  CA-2020-169194  20-06-2020  25-06-2020
48  CA-2020-169194  20-06-2020  25-06-2020
49  CA-2019-115742  18-04-2019  22-04-2019

In [27]:
df_new = df[['order_id','order_date','ship_date']]

In [32]:
df_new

          order_id  order_date   ship_date
0   CA-2020-152156  08-11-2020  11-11-2020
1   CA-2020-152156  08-11-2020  11-11-2020
2   CA-2020-138688  12-06-2020  16-06-2020
3   US-2019-108966  11-10-2019  18-10-2019
4   US-2019-108966  11-10-2019  18-10-2019
5   CA-2018-115812  09-06-2018  14-06-2018
6   CA-2018-115812  09-06-2018  14-06-2018
7   CA-2018-115812  09-06-2018  14-06-2018
8   CA-2018-115812  09-06-2018  14-06-2018
9   CA-2018-115812  09-06-2018  14-06-2018
10  CA-2018-115812  09-06-2018  14-06-2018
11  CA-2018-115812  09-06-2018  14-06-2018
12  CA-2021-114412  15-04-2021  20-04-2021
13  CA-2020-161389  05-12-2020  10-12-2020
14  US-2019-118983  22-11-2019  26-11-2019
15  US-2019-118983  22-11-2019  26-11-2019
16  CA-2018-105893  11-11-2018  18-11-2018
17  CA-2018-167164  13-05-2018  15-05-2018
18  CA-2018-143336  27-08-2018  01-09-2018
19  CA-2018-143336  27-08-2018  01-09-2018
20  CA-2018-143336  27-08-2018  01-09-2018
21  CA-2020-137330  09-12-2020  13-12-2020
22  CA-2020-137330  09-12-2020  13-12-2020
23  US-2021-156909  16-07-2021  18-07-2021
24  CA-2019-106320  25-09-2019  30-09-2019
25  CA-2020-121755  16-01-2020  20-01-2020
26  CA-2020-121755  16-01-2020  20-01-2020
27  US-2019-150630  17-09-2019  21-09-2019
28  US-2019-150630  17-09-2019  21-09-2019
29  US-2019-150630  17-09-2019  21-09-2019
30  US-2019-150630  17-09-2019  21-09-2019
31  US-2019-150630  17-09-2019  21-09-2019
32  US-2019-150630  17-09-2019  21-09-2019
33  US-2019-150630  17-09-2019  21-09-2019
34  CA-2021-107727  19-10-2021  23-10-2021
35  CA-2020-117590  08-12-2020  10-12-2020
36  CA-2020-117590  08-12-2020  10-12-2020
37  CA-2019-117415  27-12-2019  31-12-2019
38  CA-2019-117415  27-12-2019  31-12-2019
39  CA-2019-117415  27-12-2019  31-12-2019
40  CA-2019-117415  27-12-2019  31-12-2019
41  CA-2021-120999  10-09-2021  15-09-2021
42  CA-2020-101343  17-07-2020  22-07-2020
43  CA-2021-139619  19-09-2021  23-09-2021
44  CA-2020-118255  11-03-2020  13-03-2020
45  CA-2020-118255  11-03-2020  13-03-2020
46  CA-2018-146703  20-10-2018  25-10-2018
47  CA-2020-169194  20-06-2020  25-06-2020
48  CA-2020-169194  20-06-2020  25-06-2020
49  CA-2019-115742  18-04-2019  22-04-2019

In [33]:
df['order_id'] # for single column

0     CA-2020-152156
1     CA-2020-152156
2     CA-2020-138688
3     US-2019-108966
4     US-2019-108966
5     CA-2018-115812
6     CA-2018-115812
7     CA-2018-115812
8     CA-2018-115812
9     CA-2018-115812
10    CA-2018-115812
11    CA-2018-115812
12    CA-2021-114412
13    CA-2020-161389
14    US-2019-118983
15    US-2019-118983
16    CA-2018-105893
17    CA-2018-167164
18    CA-2018-143336
19    CA-2018-143336
20    CA-2018-143336
21    CA-2020-137330
22    CA-2020-137330
23    US-2021-156909
24    CA-2019-106320
25    CA-2020-121755
26    CA-2020-121755
27    US-2019-150630
28    US-2019-150630
29    US-2019-150630
30    US-2019-150630
31    US-2019-150630
32    US-2019-150630
33    US-2019-150630
34    CA-2021-107727
35    CA-2020-117590
36    CA-2020-117590
37    CA-2019-117415
38    CA-2019-117415
39    CA-2019-117415
40    CA-2019-117415
41    CA-2021-120999
42    CA-2020-101343
43    CA-2021-139619
44    CA-2020-118255
45    CA-2020-118255
46    CA-2018-146703
47    CA-2020-169194
48    CA-2020-169194
49    CA-2019-115742
Name: order_id, dtype: object

In [34]:
type(df)

pandas.core.frame.DataFrame

In [37]:
df_new = df['order_id']
type(df_new) # Dataframe with a single column is a series

pandas.core.series.Series

In [38]:
df_new

0     CA-2020-152156
1     CA-2020-152156
2     CA-2020-138688
3     US-2019-108966
4     US-2019-108966
5     CA-2018-115812
6     CA-2018-115812
7     CA-2018-115812
8     CA-2018-115812
9     CA-2018-115812
10    CA-2018-115812
11    CA-2018-115812
12    CA-2021-114412
13    CA-2020-161389
14    US-2019-118983
15    US-2019-118983
16    CA-2018-105893
17    CA-2018-167164
18    CA-2018-143336
19    CA-2018-143336
20    CA-2018-143336
21    CA-2020-137330
22    CA-2020-137330
23    US-2021-156909
24    CA-2019-106320
25    CA-2020-121755
26    CA-2020-121755
27    US-2019-150630
28    US-2019-150630
29    US-2019-150630
30    US-2019-150630
31    US-2019-150630
32    US-2019-150630
33    US-2019-150630
34    CA-2021-107727
35    CA-2020-117590
36    CA-2020-117590
37    CA-2019-117415
38    CA-2019-117415
39    CA-2019-117415
40    CA-2019-117415
41    CA-2021-120999
42    CA-2020-101343
43    CA-2021-139619
44    CA-2020-118255
45    CA-2020-118255
46    CA-2018-146703
47    CA-2020-169194
48    CA-2020-169194
49    CA-2019-115742
Name: order_id, dtype: object

In [39]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [41]:
df.iloc[0:5]  # i = index , loc = location

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5

In [42]:
df.iloc[3:5]

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5

In [43]:
df.iloc[3:]

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [44]:
df.iloc[:11]

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3

In [45]:
df.iloc[[2,5,8]] # only gives particular columns

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8

In [46]:
df.iloc[[2,5,8] , 0:4]

         order_id  order_date   ship_date       ship_mode
2  CA-2020-138688  12-06-2020  16-06-2020    Second Class
5  CA-2018-115812  09-06-2018  14-06-2018  Standard Class
8  CA-2018-115812  09-06-2018  14-06-2018  Standard Class

In [48]:
df.iloc[[2,5,8] , 5:7]

  region       product_id
2   West  OFF-LA-10000240
5   West  FUR-FU-10001487
8   West  OFF-BI-10003910

In [49]:
df.iloc[[2,5,8] , [2,4,6]]

    ship_date customer_id       product_id
2  16-06-2020    DV-13045  OFF-LA-10000240
5  14-06-2018    BH-11710  FUR-FU-10001487
8  14-06-2018    BH-11710  OFF-BI-10003910

In [51]:
df.loc[0:10,['order_id','order_date','sales']]

          order_id  order_date   sales
0   CA-2020-152156  08-11-2020   262.0
1   CA-2020-152156  08-11-2020   731.9
2   CA-2020-138688  12-06-2020    14.6
3   US-2019-108966  11-10-2019   957.6
4   US-2019-108966  11-10-2019    22.4
5   CA-2018-115812  09-06-2018    48.9
6   CA-2018-115812  09-06-2018     7.3
7   CA-2018-115812  09-06-2018   907.2
8   CA-2018-115812  09-06-2018    18.5
9   CA-2018-115812  09-06-2018   114.9
10  CA-2018-115812  09-06-2018  1706.2

In [52]:
df_new = df.loc[0:10,['order_id','order_date','sales']]

In [53]:
df_new

          order_id  order_date   sales
0   CA-2020-152156  08-11-2020   262.0
1   CA-2020-152156  08-11-2020   731.9
2   CA-2020-138688  12-06-2020    14.6
3   US-2019-108966  11-10-2019   957.6
4   US-2019-108966  11-10-2019    22.4
5   CA-2018-115812  09-06-2018    48.9
6   CA-2018-115812  09-06-2018     7.3
7   CA-2018-115812  09-06-2018   907.2
8   CA-2018-115812  09-06-2018    18.5
9   CA-2018-115812  09-06-2018   114.9
10  CA-2018-115812  09-06-2018  1706.2

In [64]:
df.set_index('order_id',inplace=True) # by this order_id work as index

In [65]:
df

,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
order_id,,,,,,,,,,
CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [68]:
df.loc['CA-2020-152156','order_date':'customer_id']

                order_date   ship_date     ship_mode customer_id
order_id
CA-2020-152156  08-11-2020  11-11-2020  Second Class    CG-12520
CA-2020-152156  08-11-2020  11-11-2020  Second Class    CG-12520

In [70]:
# These can't work in .iloc
# df.iloc['CA-2020-152156','order_date':'customer_id']
# df.iloc['CA-2020-152156',0:2]

In [71]:
df.loc[['CA-2021-107727','CA-2020-117590'],['ship_date','order_date']]

                 ship_date  order_date
order_id
CA-2021-107727  23-10-2021  19-10-2021
CA-2020-117590  10-12-2020  08-12-2020
CA-2020-117590  10-12-2020  08-12-2020

In [73]:
# reset index
df.reset_index(inplace=True)

In [74]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [79]:
# sorting dataframe

#df.sort_index() # already sort
#df.sort_index(ascending=False)
#df.sort_index(ascending=False,inplace=True)
df.sort_index(ascending=True,inplace=True)

In [80]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [89]:
#df.sort_values('sales',ascending=False) # by default in ascending order
df.sort_values(['quantity','profit'],ascending=[True,False] , inplace=True)

In [90]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4

In [91]:
df.reset_index() # By doing this,it make two index first is new and second is previous one result index.

,index,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
2,17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
3,43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
4,45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
5,2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
6,48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
7,25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
8,42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
9,33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
10,4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
11,18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
12,30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
13,23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
14,28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
15,24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
16,1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
17,13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
18,19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
19,29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
20,26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
21,34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
22,8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
23,12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
24,47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
25,15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
26,39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
27,38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
28,11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
29,40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
30,41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
31,46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
32,20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
33,6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
34,9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
35,14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
36,36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
38,7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
39,49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0
40,16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
41,31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
42,32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
43,35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
44,22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
45,5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
46,21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
47,27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
48,10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
49,37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4

In [93]:
# if dont want previous result index then,
df.reset_index(drop=True,inplace=True)

In [94]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
2,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
3,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
4,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
5,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
6,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
7,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
8,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
9,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
10,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
11,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
12,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
13,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
14,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
15,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
16,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
17,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
19,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
20,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
21,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
22,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
23,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
24,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
25,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
26,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
27,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
28,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
29,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
30,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
31,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
32,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
33,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
34,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
35,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
38,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
39,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0
40,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
41,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
42,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
43,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
44,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
45,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
46,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
47,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
48,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
49,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4

In [98]:
# data Filteration
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
2,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
3,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
4,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
5,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
6,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
7,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
8,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
9,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
10,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
11,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
12,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
13,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
14,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
15,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
16,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
17,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
19,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
20,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
21,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
22,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
23,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
24,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
25,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
26,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
27,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
28,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
29,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
30,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
31,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
32,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
33,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
34,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
35,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
38,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
39,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0
40,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
41,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
42,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
43,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
44,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
45,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
46,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
47,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
48,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
49,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4

In [100]:
fc = df['region']=='South'
df.loc[fc]

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
3,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
10,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
16,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
23,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
37,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0

In [101]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
2,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
3,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
4,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
5,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
6,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
7,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
8,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
9,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
10,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
11,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
12,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
13,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
14,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
15,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
16,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
17,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
19,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
20,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
21,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
22,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
23,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
24,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
25,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
26,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
27,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
28,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
29,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
30,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
31,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
32,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
33,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
34,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
35,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
38,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
39,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0
40,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
41,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
42,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
43,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
44,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
45,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
46,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
47,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
48,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
49,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4

In [103]:
df['region']=='South' #

0      True
1     False
2     False
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11    False
12    False
13    False
14    False
15    False
16     True
17    False
18    False
19    False
20    False
21    False
22    False
23     True
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37     True
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
Name: region, dtype: bool

In [104]:
type(df['region']=='South')

pandas.core.series.Series

In [105]:
df.loc[df['region']=='South',['order_id','order_date']]

          order_id  order_date
0   CA-2020-152156  08-11-2020
3   CA-2021-139619  19-09-2021
10  US-2019-108966  11-10-2019
16  CA-2020-152156  08-11-2020
23  CA-2021-114412  15-04-2021
37  US-2019-108966  11-10-2019

In [109]:
df.loc[(df['region'] == 'South') & (df['profit'] > 0)]

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
3,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
10,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
16,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
23,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4

In [110]:
df.loc[(df['region'] == 'South') | (df['profit'] > 0)]

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
2,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
3,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
4,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
5,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
6,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
7,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
8,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
9,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
10,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
11,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
12,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
15,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
16,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
17,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
19,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
20,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
21,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
22,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
23,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
24,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
28,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
29,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
30,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
31,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
32,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
33,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
34,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
37,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
38,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
39,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0
40,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
41,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
43,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
44,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
45,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
46,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
48,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
49,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4

In [111]:
# when you want all the columns
df[df['region']=='South']

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
3,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
10,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
16,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
23,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
37,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0

In [113]:
# Inverse a condition
df[~(df['region']=='South')] # It gives results other than condition

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
1,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
2,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
4,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
5,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
6,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
7,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
8,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
9,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
11,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
12,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
13,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
14,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
15,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
17,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
19,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
20,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
21,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
22,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
24,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
25,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
26,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
27,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
28,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
29,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
30,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
31,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
32,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
33,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
34,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
35,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
38,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
39,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0
40,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
41,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
42,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
43,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
44,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
45,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
46,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
47,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
48,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
49,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4

**Adding,Updating & Deleting Columns**

In [114]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
2,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
3,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
4,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
5,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
6,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
7,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
8,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
9,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
10,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
11,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
12,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
13,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
14,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
15,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
16,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
17,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
19,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
20,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
21,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
22,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
23,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
24,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
25,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
26,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
27,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
28,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
29,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
30,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
31,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
32,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
33,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
34,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
35,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
38,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
39,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0
40,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
41,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
42,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
43,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
44,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
45,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
46,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
47,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
48,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
49,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4

In [115]:
df['country'] = 'India' # Add new column

In [117]:
df['country'] = 'USA' # update new column

In [118]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,country
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9,USA
1,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8,USA
2,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0,USA
3,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6,USA
4,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2,USA
5,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9,USA
6,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1,USA
7,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2,USA
8,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9,USA
9,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5,USA
10,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5,USA
11,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5,USA
12,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1,USA
13,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0,USA
14,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1,USA
15,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3,USA
16,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6,USA
17,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6,USA
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0,USA
19,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5,USA
20,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8,USA
21,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9,USA
22,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8,USA
23,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4,USA
24,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0,USA
25,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8,USA
26,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1,USA
27,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0,USA
28,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4,USA
29,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8,USA
30,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6,USA
31,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5,USA
32,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4,USA
33,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0,USA
34,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5,USA
35,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9,USA
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0,USA
37,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0,USA
38,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7,USA
39,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0,USA
40,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3,USA
41,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7,USA
42,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7,USA
43,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5,USA
44,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7,USA
45,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2,USA
46,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1,USA
47,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1,USA
48,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3,USA
49,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4,USA

In [121]:
# Drop the column
df.drop(columns='country',inplace=True)

In [122]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
2,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
3,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
4,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
5,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
6,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
7,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
8,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
9,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
10,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
11,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
12,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
13,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
14,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
15,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
16,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
17,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
19,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
20,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
21,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
22,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
23,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
24,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
25,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
26,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
27,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
28,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
29,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
30,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
31,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
32,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
33,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
34,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
35,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
38,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
39,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0
40,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
41,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
42,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
43,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
44,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
45,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
46,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
47,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
48,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
49,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4

In [123]:
df['profit_flag'] = 1

In [124]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,profit_flag
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9,1
1,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8,1
2,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0,1
3,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6,1
4,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2,1
5,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9,1
6,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1,1
7,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2,1
8,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9,1
9,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5,1
10,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5,1
11,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5,1
12,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1,1
13,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0,1
14,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1,1
15,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3,1
16,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6,1
17,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6,1
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0,1
19,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5,1
20,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8,1
21,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9,1
22,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8,1
23,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4,1
24,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0,1
25,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8,1
26,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1,1
27,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0,1
28,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4,1
29,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8,1
30,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6,1
31,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5,1
32,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4,1
33,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0,1
34,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5,1
35,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9,1
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0,1
37,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0,1
38,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7,1
39,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0,1
40,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3,1
41,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7,1
42,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7,1
43,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5,1
44,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7,1
45,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2,1
46,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1,1
47,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1,1
48,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3,1
49,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4,1

In [126]:
df.loc[df['profit']<=0,'profit_flag'] = 0

In [127]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,profit_flag
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9,1
1,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8,1
2,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0,1
3,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6,1
4,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2,1
5,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9,1
6,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1,1
7,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2,1
8,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9,1
9,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5,1
10,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5,1
11,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5,1
12,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1,1
13,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0,0
14,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1,0
15,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3,1
16,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6,1
17,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6,1
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0,1
19,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5,1
20,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8,1
21,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9,1
22,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8,1
23,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4,1
24,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0,1
25,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8,0
26,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1,0
27,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0,0
28,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4,1
29,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8,1
30,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6,1
31,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5,1
32,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4,1
33,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0,1
34,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5,1
35,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9,0
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0,0
37,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0,0
38,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7,1
39,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0,1
40,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3,1
41,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7,1
42,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7,0
43,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5,1
44,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7,1
45,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2,1
46,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1,1
47,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1,0
48,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3,1
49,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4,1

In [ ]:
# create a new column with these value (Assignment)
# < 0 -> loss
# between 0 and 50 -> low profit
# > 50 -> high profit

In [128]:
df.drop(columns='profit_flag',inplace=True)

In [129]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
2,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
3,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
4,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
5,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
6,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
7,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
8,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
9,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
10,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
11,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
12,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
13,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
14,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
15,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
16,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
17,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
19,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
20,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
21,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
22,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
23,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
24,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
25,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
26,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
27,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
28,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
29,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
30,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
31,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
32,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
33,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
34,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
35,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
38,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
39,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0
40,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
41,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
42,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
43,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
44,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
45,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
46,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
47,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
48,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
49,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4

In [131]:
df['category_len'] = df['category'].apply(len)

In [132]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,category_len
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9,9
1,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8,10
2,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0,15
3,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6,15
4,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2,15
5,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9,15
6,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1,10
7,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2,15
8,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9,15
9,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5,15
10,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5,15
11,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5,15
12,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1,15
13,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0,9
14,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1,15
15,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3,9
16,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6,9
17,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6,15
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0,10
19,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5,9
20,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8,10
21,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9,15
22,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8,15
23,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4,15
24,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0,10
25,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8,15
26,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1,9
27,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0,9
28,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4,10
29,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8,10
30,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6,10
31,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5,15
32,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4,15
33,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0,15
34,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5,15
35,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9,15
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0,9
37,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0,9
38,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7,10
39,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0,15
40,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3,15
41,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7,15
42,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7,15
43,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5,10
44,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7,15
45,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2,9
46,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1,15
47,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1,9
48,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3,9
49,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4,15

In [135]:
def profit_loss(profit):
    if profit>0:
        return "profit"
    else:
        return "loss"
df['profit_loss'] = df['profit'].apply(profit_loss)

In [136]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,category_len,profit_loss
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9,9,profit
1,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8,10,profit
2,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0,15,profit
3,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6,15,profit
4,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2,15,profit
5,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9,15,profit
6,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1,10,profit
7,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2,15,profit
8,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9,15,profit
9,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5,15,profit
10,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5,15,profit
11,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5,15,profit
12,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1,15,profit
13,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0,9,loss
14,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1,15,loss
15,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3,9,profit
16,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6,9,profit
17,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6,15,profit
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0,10,profit
19,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5,9,profit
20,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8,10,profit
21,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9,15,profit
22,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8,15,profit
23,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4,15,profit
24,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0,10,profit
25,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8,15,loss
26,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1,9,loss
27,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0,9,loss
28,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4,10,profit
29,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8,10,profit
30,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6,10,profit
31,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5,15,profit
32,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4,15,profit
33,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0,15,profit
34,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5,15,profit
35,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9,15,loss
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0,9,loss
37,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0,9,loss
38,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7,10,profit
39,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0,15,profit
40,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3,15,profit
41,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7,15,profit
42,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7,15,loss
43,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5,10,profit
44,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7,15,profit
45,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2,9,profit
46,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1,15,profit
47,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1,9,loss
48,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3,9,profit
49,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4,15,profit

In [137]:
name = 'Ankit'
type(name)

str

In [138]:
name.upper()

'ANKIT'

In [139]:
name.lower()

'ankit'

In [140]:
name.startswith('A')

True

In [141]:
name.endswith('b')

False

In [ ]:
# df['category'].upper() # it is a series so it doesn't work

In [143]:
df['Category_upper'] = df['category'].str.upper()

In [144]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,category_len,profit_loss,Category_upper
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9,9,profit,FURNITURE
1,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8,10,profit,TECHNOLOGY
2,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0,15,profit,OFFICE SUPPLIES
3,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6,15,profit,OFFICE SUPPLIES
4,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2,15,profit,OFFICE SUPPLIES
5,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9,15,profit,OFFICE SUPPLIES
6,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1,10,profit,TECHNOLOGY
7,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2,15,profit,OFFICE SUPPLIES
8,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9,15,profit,OFFICE SUPPLIES
9,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5,15,profit,OFFICE SUPPLIES
10,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5,15,profit,OFFICE SUPPLIES
11,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5,15,profit,OFFICE SUPPLIES
12,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1,15,profit,OFFICE SUPPLIES
13,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0,9,loss,FURNITURE
14,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1,15,loss,OFFICE SUPPLIES
15,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3,9,profit,FURNITURE
16,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6,9,profit,FURNITURE
17,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6,15,profit,OFFICE SUPPLIES
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0,10,profit,TECHNOLOGY
19,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5,9,profit,FURNITURE
20,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8,10,profit,TECHNOLOGY
21,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9,15,profit,OFFICE SUPPLIES
22,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8,15,profit,OFFICE SUPPLIES
23,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4,15,profit,OFFICE SUPPLIES
24,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0,10,profit,TECHNOLOGY
25,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8,15,loss,OFFICE SUPPLIES
26,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1,9,loss,FURNITURE
27,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0,9,loss,FURNITURE
28,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4,10,profit,TECHNOLOGY
29,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8,10,profit,TECHNOLOGY
30,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6,10,profit,TECHNOLOGY
31,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5,15,profit,OFFICE SUPPLIES
32,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4,15,profit,OFFICE SUPPLIES
33,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0,15,profit,OFFICE SUPPLIES
34,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5,15,profit,OFFICE SUPPLIES
35,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9,15,loss,OFFICE SUPPLIES
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0,9,loss,FURNITURE
37,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0,9,loss,FURNITURE
38,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7,10,profit,TECHNOLOGY
39,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0,15,profit,OFFICE SUPPLIES
40,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3,15,profit,OFFICE SUPPLIES
41,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7,15,profit,OFFICE SUPPLIES
42,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7,15,loss,OFFICE SUPPLIES
43,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5,10,profit,TECHNOLOGY
44,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7,15,profit,OFFICE SUPPLIES
45,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2,9,profit,FURNITURE
46,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1,15,profit,OFFICE SUPPLIES
47,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1,9,loss,FURNITURE
48,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3,9,profit,FURNITURE
49,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4,15,profit,OFFICE SUPPLIES

In [146]:
df.drop(columns=['category_len','profit_loss','Category_upper'],inplace=True)

In [147]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
2,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
3,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
4,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
5,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
6,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
7,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
8,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
9,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
10,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
11,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
12,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
13,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
14,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
15,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
16,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
17,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
19,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
20,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
21,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
22,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
23,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
24,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
25,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
26,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
27,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
28,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
29,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
30,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
31,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
32,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
33,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
34,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
35,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
38,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
39,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0
40,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
41,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
42,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
43,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
44,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
45,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
46,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
47,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
48,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
49,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4

In [149]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,NaN,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,NaN,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

**Handling Missing values in pandas and drop duplicates**

In [150]:
# df.isnull()		# returns True/False for each cell,it show NaN value True rest are False

df.isnull()

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,False,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False,False,False,False
39,False,False,False,False,False,False,False,False,False,False,False
40,False,False,False,False,False,False,False,False,False,False,False
41,False,False,False,False,False,False,False,False,False,False,False
42,False,False,False,False,False,False,False,False,False,False,False
43,False,False,False,False,False,False,False,False,False,False,False
44,False,False,False,False,False,False,False,False,False,False,False
45,False,False,False,False,False,False,False,False,False,False,False
46,False,False,False,False,False,False,False,False,False,False,False
47,False,False,False,False,False,False,False,False,False,False,False
48,False,False,False,False,False,False,False,False,False,False,False
49,False,False,False,False,False,False,False,False,False,False,False

In [151]:
# df.isnull().sum()	# total missing per column
df.isnull().sum()

order_id       0
order_date     0
ship_date      0
ship_mode      1
customer_id    0
region         0
product_id     0
category       1
sales          0
quantity       0
profit         0
dtype: int64

In [152]:
# df.info()    # quick view of non-null counts
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     50 non-null     object
 1   order_date   50 non-null     object
 2   ship_date    50 non-null     object
 3   ship_mode    49 non-null     object
 4   customer_id  50 non-null     object
 5   region       50 non-null     object
 6   product_id   50 non-null     object
 7   category     49 non-null     object
 8   sales        50 non-null     float64
 9   quantity     50 non-null     int64
 10  profit       50 non-null     float64
dtypes: float64(2), int64(1), object(8)
memory usage: 4.4+ KB

In [155]:
# df.dropna(inplace=True) 		# removes rows with any missing value or those have NaN value
df.dropna()

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [159]:
# df.dropna(subset=[“sales”])		# removes rows where sales is missing
df.dropna(subset=["category","ship_mode"])

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [160]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,NaN,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,NaN,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [162]:
df.fillna("unknown",inplace = True)

In [163]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,unknown,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,unknown,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [179]:
# duplicates
data = {
    "name":["Sumit","Rahul","Ankit","Ankit","Ankit"],
    "age":[25,30,30,30,30],
    "salary" : [25000,30000,35000,35000,35000]
}
df = pd.DataFrame(data)

In [173]:
df

    name  age  salary
0  Sumit   25   25000
1  Rahul   30   30000
2  Ankit   30   35000
3  Ankit   30   35000

In [175]:
df.drop_duplicates()

    name  age  salary
0  Sumit   25   25000
1  Rahul   30   30000
2  Ankit   30   35000

In [176]:
df

    name  age  salary
0  Sumit   25   25000
1  Rahul   30   30000
2  Ankit   30   35000
3  Ankit   30   35000

In [177]:
df.drop_duplicates(keep = 'last')

    name  age  salary
0  Sumit   25   25000
1  Rahul   30   30000
3  Ankit   30   35000

In [178]:
df.drop_duplicates(keep = 'first')

    name  age  salary
0  Sumit   25   25000
1  Rahul   30   30000
2  Ankit   30   35000

In [180]:
df

    name  age  salary
0  Sumit   25   25000
1  Rahul   30   30000
2  Ankit   30   35000
3  Ankit   30   35000
4  Ankit   30   35000

In [181]:
df.drop_duplicates(subset = 'age')

    name  age  salary
0  Sumit   25   25000
1  Rahul   30   30000

In [182]:
df.drop_duplicates(subset = 'age' , keep = 'last')

    name  age  salary
0  Sumit   25   25000
4  Ankit   30   35000

In [185]:
df.drop_duplicates(subset = ['age','salary'], keep = 'first')

    name  age  salary
0  Sumit   25   25000
1  Rahul   30   30000
2  Ankit   30   35000

**Date and Times with Pandas**

In [190]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,NaN,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,NaN,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [192]:
df["order_date"] = pd.to_datetime(df["order_date"], format = '%d-%m-%Y')

In [193]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,2020-11-08,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,NaN,262.0,2,41.9
1,CA-2020-152156,2020-11-08,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,2020-06-12,16-06-2020,NaN,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,2019-10-11,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,2019-10-11,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,2018-06-09,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,2018-06-09,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,2018-06-09,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,2018-06-09,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,2018-06-09,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,2018-06-09,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,2018-06-09,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
12,CA-2021-114412,2021-04-15,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,2020-12-05,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
14,US-2019-118983,2019-11-22,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
15,US-2019-118983,2019-11-22,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
16,CA-2018-105893,2018-11-11,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
17,CA-2018-167164,2018-05-13,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,2018-08-27,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
19,CA-2018-143336,2018-08-27,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
20,CA-2018-143336,2018-08-27,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2020-137330,2020-12-09,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
22,CA-2020-137330,2020-12-09,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
23,US-2021-156909,2021-07-16,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,2019-09-25,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
25,CA-2020-121755,2020-01-16,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,2020-01-16,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
27,US-2019-150630,2019-09-17,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
28,US-2019-150630,2019-09-17,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
29,US-2019-150630,2019-09-17,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
30,US-2019-150630,2019-09-17,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
31,US-2019-150630,2019-09-17,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,2019-09-17,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
33,US-2019-150630,2019-09-17,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
34,CA-2021-107727,2021-10-19,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,2020-12-08,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,2020-12-08,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,CA-2019-117415,2019-12-27,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
38,CA-2019-117415,2019-12-27,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,2019-12-27,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
40,CA-2019-117415,2019-12-27,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,2021-09-10,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,2020-07-17,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,2021-09-19,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,2020-03-11,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,2020-03-11,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,2018-10-20,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,2020-06-20,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,2020-06-20,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,2019-04-18,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [194]:
df.dtypes

order_id               object
order_date     datetime64[ns]
ship_date              object
ship_mode              object
customer_id            object
region                 object
product_id             object
category               object
sales                 float64
quantity                int64
profit                float64
dtype: object

In [195]:
df["ship_date"] = pd.to_datetime(df["ship_date"], format = '%d-%m-%Y')

In [196]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,2020-11-08,2020-11-11,Second Class,CG-12520,South,FUR-BO-10001798,NaN,262.0,2,41.9
1,CA-2020-152156,2020-11-08,2020-11-11,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,2020-06-12,2020-06-16,NaN,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,2019-10-11,2019-10-18,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,2019-10-11,2019-10-18,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
12,CA-2021-114412,2021-04-15,2021-04-20,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,2020-12-05,2020-12-10,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
14,US-2019-118983,2019-11-22,2019-11-26,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
15,US-2019-118983,2019-11-22,2019-11-26,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
16,CA-2018-105893,2018-11-11,2018-11-18,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
17,CA-2018-167164,2018-05-13,2018-05-15,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,2018-08-27,2018-09-01,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
19,CA-2018-143336,2018-08-27,2018-09-01,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
20,CA-2018-143336,2018-08-27,2018-09-01,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2020-137330,2020-12-09,2020-12-13,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
22,CA-2020-137330,2020-12-09,2020-12-13,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
23,US-2021-156909,2021-07-16,2021-07-18,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,2019-09-25,2019-09-30,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
25,CA-2020-121755,2020-01-16,2020-01-20,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,2020-01-16,2020-01-20,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
27,US-2019-150630,2019-09-17,2019-09-21,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
28,US-2019-150630,2019-09-17,2019-09-21,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
29,US-2019-150630,2019-09-17,2019-09-21,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
30,US-2019-150630,2019-09-17,2019-09-21,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
31,US-2019-150630,2019-09-17,2019-09-21,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,2019-09-17,2019-09-21,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
33,US-2019-150630,2019-09-17,2019-09-21,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
34,CA-2021-107727,2021-10-19,2021-10-23,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,2020-12-08,2020-12-10,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,2020-12-08,2020-12-10,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,CA-2019-117415,2019-12-27,2019-12-31,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
38,CA-2019-117415,2019-12-27,2019-12-31,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,2019-12-27,2019-12-31,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
40,CA-2019-117415,2019-12-27,2019-12-31,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,2021-09-10,2021-09-15,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,2020-07-17,2020-07-22,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,2021-09-19,2021-09-23,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,2020-03-11,2020-03-13,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,2020-03-11,2020-03-13,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,2018-10-20,2018-10-25,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,2020-06-20,2020-06-25,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,2020-06-20,2020-06-25,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,2019-04-18,2019-04-22,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [198]:
df.dtypes

order_id               object
order_date     datetime64[ns]
ship_date      datetime64[ns]
ship_mode              object
customer_id            object
region                 object
product_id             object
category               object
sales                 float64
quantity                int64
profit                float64
dtype: object

In [200]:
df['order_year'] = df['order_date'].dt.year

In [203]:
df['order_month'] = df['order_date'].dt.month

In [201]:
df['order_day'] = df['order_date'].dt.day

In [204]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,order_year,order_day,order_month
0,CA-2020-152156,2020-11-08,2020-11-11,Second Class,CG-12520,South,FUR-BO-10001798,NaN,262.0,2,41.9,2020,8,11
1,CA-2020-152156,2020-11-08,2020-11-11,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6,2020,8,11
2,CA-2020-138688,2020-06-12,2020-06-16,NaN,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9,2020,12,6
3,US-2019-108966,2019-10-11,2019-10-18,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0,2019,11,10
4,US-2019-108966,2019-10-11,2019-10-18,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5,2019,11,10
5,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2,2018,9,6
6,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0,2018,9,6
7,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7,2018,9,6
8,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8,2018,9,6
9,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5,2018,9,6
10,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3,2018,9,6
11,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4,2018,9,6
12,CA-2021-114412,2021-04-15,2021-04-20,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4,2021,15,4
13,CA-2020-161389,2020-12-05,2020-12-10,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6,2020,5,12
14,US-2019-118983,2019-11-22,2019-11-26,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9,2019,22,11
15,US-2019-118983,2019-11-22,2019-11-26,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8,2019,22,11
16,CA-2018-105893,2018-11-11,2018-11-18,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3,2018,11,11
17,CA-2018-167164,2018-05-13,2018-05-15,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0,2018,13,5
18,CA-2018-143336,2018-08-27,2018-09-01,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5,2018,27,8
19,CA-2018-143336,2018-08-27,2018-09-01,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0,2018,27,8
20,CA-2018-143336,2018-08-27,2018-09-01,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4,2018,27,8
21,CA-2020-137330,2020-12-09,2020-12-13,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1,2020,9,12
22,CA-2020-137330,2020-12-09,2020-12-13,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7,2020,9,12
23,US-2021-156909,2021-07-16,2021-07-18,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0,2021,16,7
24,CA-2019-106320,2019-09-25,2019-09-30,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3,2019,25,9
25,CA-2020-121755,2020-01-16,2020-01-20,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2,2020,16,1
26,CA-2020-121755,2020-01-16,2020-01-20,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8,2020,16,1
27,US-2019-150630,2019-09-17,2019-09-21,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1,2019,17,9
28,US-2019-150630,2019-09-17,2019-09-21,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1,2019,17,9
29,US-2019-150630,2019-09-17,2019-09-21,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5,2019,17,9
30,US-2019-150630,2019-09-17,2019-09-21,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1,2019,17,9
31,US-2019-150630,2019-09-17,2019-09-21,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7,2019,17,9
32,US-2019-150630,2019-09-17,2019-09-21,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7,2019,17,9
33,US-2019-150630,2019-09-17,2019-09-21,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5,2019,17,9
34,CA-2021-107727,2021-10-19,2021-10-23,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9,2021,19,10
35,CA-2020-117590,2020-12-08,2020-12-10,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5,2020,8,12
36,CA-2020-117590,2020-12-08,2020-12-10,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0,2020,8,12
37,CA-2019-117415,2019-12-27,2019-12-31,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4,2019,27,12
38,CA-2019-117415,2019-12-27,2019-12-31,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0,2019,27,12
39,CA-2019-117415,2019-12-27,2019-12-31,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1,2019,27,12
40,CA-2019-117415,2019-12-27,2019-12-31,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8,2019,27,12
41,CA-2021-120999,2021-09-10,2021-09-15,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6,2021,10,9
42,CA-2020-101343,2020-07-17,2020-07-22,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9,2020,17,7
43,CA-2021-139619,2021-09-19,2021-09-23,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6,2021,19,9
44,CA-2020-118255,2020-03-11,2020-03-13,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8,2020,11,3
45,CA-2020-118255,2020-03-11,2020-03-13,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2,2020,11,3
46,CA-2018-146703,2018-10-20,2018-10-25,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5,2018,20,10
47,CA-2020-169194,2020-06-20,2020-06-25,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0,2020,20,6
48,CA-2020-169194,2020-06-20,2020-06-25,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1,2020,20,6
49,CA-2019-115742,2019-04-18,2019-04-22,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0,2019,18,4

In [205]:
df[df['order_date'] >= '2021-02-01']

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,order_year,order_day,order_month
12,CA-2021-114412,2021-04-15,2021-04-20,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4,2021,15,4
23,US-2021-156909,2021-07-16,2021-07-18,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0,2021,16,7
34,CA-2021-107727,2021-10-19,2021-10-23,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9,2021,19,10
41,CA-2021-120999,2021-09-10,2021-09-15,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6,2021,10,9
43,CA-2021-139619,2021-09-19,2021-09-23,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6,2021,19,9

In [206]:
df["transit_days"] = (df["ship_date"] - df["order_date"]).dt.days

In [207]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,order_year,order_day,order_month,transit_days
0,CA-2020-152156,2020-11-08,2020-11-11,Second Class,CG-12520,South,FUR-BO-10001798,NaN,262.0,2,41.9,2020,8,11,3
1,CA-2020-152156,2020-11-08,2020-11-11,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6,2020,8,11,3
2,CA-2020-138688,2020-06-12,2020-06-16,NaN,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9,2020,12,6,4
3,US-2019-108966,2019-10-11,2019-10-18,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0,2019,11,10,7
4,US-2019-108966,2019-10-11,2019-10-18,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5,2019,11,10,7
5,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2,2018,9,6,5
6,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0,2018,9,6,5
7,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7,2018,9,6,5
8,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8,2018,9,6,5
9,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5,2018,9,6,5
10,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3,2018,9,6,5
11,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4,2018,9,6,5
12,CA-2021-114412,2021-04-15,2021-04-20,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4,2021,15,4,5
13,CA-2020-161389,2020-12-05,2020-12-10,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6,2020,5,12,5
14,US-2019-118983,2019-11-22,2019-11-26,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9,2019,22,11,4
15,US-2019-118983,2019-11-22,2019-11-26,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8,2019,22,11,4
16,CA-2018-105893,2018-11-11,2018-11-18,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3,2018,11,11,7
17,CA-2018-167164,2018-05-13,2018-05-15,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0,2018,13,5,2
18,CA-2018-143336,2018-08-27,2018-09-01,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5,2018,27,8,5
19,CA-2018-143336,2018-08-27,2018-09-01,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0,2018,27,8,5
20,CA-2018-143336,2018-08-27,2018-09-01,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4,2018,27,8,5
21,CA-2020-137330,2020-12-09,2020-12-13,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1,2020,9,12,4
22,CA-2020-137330,2020-12-09,2020-12-13,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7,2020,9,12,4
23,US-2021-156909,2021-07-16,2021-07-18,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0,2021,16,7,2
24,CA-2019-106320,2019-09-25,2019-09-30,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3,2019,25,9,5
25,CA-2020-121755,2020-01-16,2020-01-20,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2,2020,16,1,4
26,CA-2020-121755,2020-01-16,2020-01-20,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8,2020,16,1,4
27,US-2019-150630,2019-09-17,2019-09-21,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1,2019,17,9,4
28,US-2019-150630,2019-09-17,2019-09-21,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1,2019,17,9,4
29,US-2019-150630,2019-09-17,2019-09-21,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5,2019,17,9,4
30,US-2019-150630,2019-09-17,2019-09-21,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1,2019,17,9,4
31,US-2019-150630,2019-09-17,2019-09-21,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7,2019,17,9,4
32,US-2019-150630,2019-09-17,2019-09-21,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7,2019,17,9,4
33,US-2019-150630,2019-09-17,2019-09-21,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5,2019,17,9,4
34,CA-2021-107727,2021-10-19,2021-10-23,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9,2021,19,10,4
35,CA-2020-117590,2020-12-08,2020-12-10,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5,2020,8,12,2
36,CA-2020-117590,2020-12-08,2020-12-10,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0,2020,8,12,2
37,CA-2019-117415,2019-12-27,2019-12-31,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4,2019,27,12,4
38,CA-2019-117415,2019-12-27,2019-12-31,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0,2019,27,12,4
39,CA-2019-117415,2019-12-27,2019-12-31,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1,2019,27,12,4
40,CA-2019-117415,2019-12-27,2019-12-31,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8,2019,27,12,4
41,CA-2021-120999,2021-09-10,2021-09-15,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6,2021,10,9,5
42,CA-2020-101343,2020-07-17,2020-07-22,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9,2020,17,7,5
43,CA-2021-139619,2021-09-19,2021-09-23,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6,2021,19,9,4
44,CA-2020-118255,2020-03-11,2020-03-13,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8,2020,11,3,2
45,CA-2020-118255,2020-03-11,2020-03-13,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2,2020,11,3,2
46,CA-2018-146703,2018-10-20,2018-10-25,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5,2018,20,10,5
47,CA-2020-169194,2020-06-20,2020-06-25,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0,2020,20,6,5
48,CA-2020-169194,2020-06-20,2020-06-25,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1,2020,20,6,5
49,CA-2019-115742,2019-04-18,2019-04-22,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0,2019,18,4,4

**Aggregation**

In [208]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,order_year,order_day,order_month,transit_days
0,CA-2020-152156,2020-11-08,2020-11-11,Second Class,CG-12520,South,FUR-BO-10001798,NaN,262.0,2,41.9,2020,8,11,3
1,CA-2020-152156,2020-11-08,2020-11-11,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6,2020,8,11,3
2,CA-2020-138688,2020-06-12,2020-06-16,NaN,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9,2020,12,6,4
3,US-2019-108966,2019-10-11,2019-10-18,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0,2019,11,10,7
4,US-2019-108966,2019-10-11,2019-10-18,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5,2019,11,10,7
5,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2,2018,9,6,5
6,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0,2018,9,6,5
7,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7,2018,9,6,5
8,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8,2018,9,6,5
9,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5,2018,9,6,5
10,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3,2018,9,6,5
11,CA-2018-115812,2018-06-09,2018-06-14,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4,2018,9,6,5
12,CA-2021-114412,2021-04-15,2021-04-20,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4,2021,15,4,5
13,CA-2020-161389,2020-12-05,2020-12-10,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6,2020,5,12,5
14,US-2019-118983,2019-11-22,2019-11-26,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9,2019,22,11,4
15,US-2019-118983,2019-11-22,2019-11-26,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8,2019,22,11,4
16,CA-2018-105893,2018-11-11,2018-11-18,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3,2018,11,11,7
17,CA-2018-167164,2018-05-13,2018-05-15,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0,2018,13,5,2
18,CA-2018-143336,2018-08-27,2018-09-01,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5,2018,27,8,5
19,CA-2018-143336,2018-08-27,2018-09-01,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0,2018,27,8,5
20,CA-2018-143336,2018-08-27,2018-09-01,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4,2018,27,8,5
21,CA-2020-137330,2020-12-09,2020-12-13,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1,2020,9,12,4
22,CA-2020-137330,2020-12-09,2020-12-13,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7,2020,9,12,4
23,US-2021-156909,2021-07-16,2021-07-18,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0,2021,16,7,2
24,CA-2019-106320,2019-09-25,2019-09-30,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3,2019,25,9,5
25,CA-2020-121755,2020-01-16,2020-01-20,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2,2020,16,1,4
26,CA-2020-121755,2020-01-16,2020-01-20,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8,2020,16,1,4
27,US-2019-150630,2019-09-17,2019-09-21,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1,2019,17,9,4
28,US-2019-150630,2019-09-17,2019-09-21,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1,2019,17,9,4
29,US-2019-150630,2019-09-17,2019-09-21,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5,2019,17,9,4
30,US-2019-150630,2019-09-17,2019-09-21,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1,2019,17,9,4
31,US-2019-150630,2019-09-17,2019-09-21,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7,2019,17,9,4
32,US-2019-150630,2019-09-17,2019-09-21,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7,2019,17,9,4
33,US-2019-150630,2019-09-17,2019-09-21,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5,2019,17,9,4
34,CA-2021-107727,2021-10-19,2021-10-23,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9,2021,19,10,4
35,CA-2020-117590,2020-12-08,2020-12-10,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5,2020,8,12,2
36,CA-2020-117590,2020-12-08,2020-12-10,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0,2020,8,12,2
37,CA-2019-117415,2019-12-27,2019-12-31,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4,2019,27,12,4
38,CA-2019-117415,2019-12-27,2019-12-31,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0,2019,27,12,4
39,CA-2019-117415,2019-12-27,2019-12-31,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1,2019,27,12,4
40,CA-2019-117415,2019-12-27,2019-12-31,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8,2019,27,12,4
41,CA-2021-120999,2021-09-10,2021-09-15,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6,2021,10,9,5
42,CA-2020-101343,2020-07-17,2020-07-22,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9,2020,17,7,5
43,CA-2021-139619,2021-09-19,2021-09-23,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6,2021,19,9,4
44,CA-2020-118255,2020-03-11,2020-03-13,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8,2020,11,3,2
45,CA-2020-118255,2020-03-11,2020-03-13,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2,2020,11,3,2
46,CA-2018-146703,2018-10-20,2018-10-25,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5,2018,20,10,5
47,CA-2020-169194,2020-06-20,2020-06-25,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0,2020,20,6,5
48,CA-2020-169194,2020-06-20,2020-06-25,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1,2020,20,6,5
49,CA-2019-115742,2019-04-18,2019-04-22,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0,2019,18,4,4

In [210]:
df["region"].nunique()	# get unique value of a column:

4

In [211]:
df["category"].unique()	# get distinct values of a column

array([nan, 'Furniture', 'Office Supplies', 'Technology'], dtype=object)

In [212]:
df['sales'].sum()

np.float64(15039.599999999999)

In [215]:
df.groupby("region")["sales"].sum()

region
Central    3824.8
East       3467.7
South      2085.1
West       5662.0
Name: sales, dtype: float64

In [217]:
# multiple aggregation at once
df.groupby("region")["sales"].agg(["min", "max","sum"])

          min     max     sum
region
Central   2.5  1097.5  3824.8
East      3.3  3083.4  3467.7
South    15.6   957.6  2085.1
West      7.3  1706.2  5662.0

In [219]:
# aggregation on multiple columns
df.groupby("category").agg({'sales': 'sum' , 'profit': 'sum'})

                  sales  profit
category
Furniture        8703.6 -1684.3
Office Supplies  2222.6   215.2
Technology       3851.4   399.7

In [220]:
df.groupby("category").agg({'sales': 'sum' , 'profit': 'mean'})

                  sales      profit
category
Furniture        8703.6 -153.118182
Office Supplies  2222.6    7.685714
Technology       3851.4   39.970000

In [223]:
# get count of each value (shortcut)
df["category"].value_counts()

category
Office Supplies    28
Furniture          11
Technology         10
Name: count, dtype: int64

**Pivot Table**

In [225]:
pd.pivot_table(
df,
index= "region",
columns = "category",
values = "sales",
aggfunc = "sum",
fill_value = 0
)

category  Furniture  Office Supplies  Technology
region
Central       935.4           1227.5      1661.9
East         3279.0            121.9        66.8
South        1689.5            133.6         0.0
West         2799.7            739.6      2122.7

In [228]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [238]:
df_orders = pd.read_csv('orders.csv')
df_returns = pd.read_csv('returns.csv')

In [239]:
df_returns

         order_id return_reason
0  CA-2018-105893   bad quality
1  CA-2018-143336    wrong item
2  CA-2018-146703    wrong item
3  CA-2018-167164         other
4  CA-2019-106320   bad quality
5  CA-2019-115742         other
6  CA-2020-101343   bad quality
7  CA-2020-117590    wrong item

In [240]:
df_orders

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [241]:
df = pd.merge(left = df_orders , right = df_returns , on = 'order_id',how = 'inner')

In [242]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,return_reason
0,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3,bad quality
1,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0,other
2,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5,wrong item
3,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0,wrong item
4,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4,wrong item
5,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3,bad quality
6,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5,wrong item
7,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0,wrong item
8,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9,bad quality
9,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5,wrong item
10,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0,other

In [243]:
df.groupby('return_reason')['sales'].sum()

return_reason
bad quality    1788.4
other            93.7
wrong item     1745.2
Name: sales, dtype: float64

In [244]:
df = pd.merge(left = df_orders , right = df_returns , on = 'order_id',how = 'left')

In [246]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,return_reason
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9,NaN
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6,NaN
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9,NaN
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0,NaN
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5,NaN
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2,NaN
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0,NaN
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7,NaN
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8,NaN
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5,NaN
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3,NaN
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4,NaN
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4,NaN
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6,NaN
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9,NaN
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8,NaN
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3,bad quality
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0,other
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5,wrong item
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0,wrong item
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4,wrong item
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1,NaN
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7,NaN
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0,NaN
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3,bad quality
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2,NaN
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8,NaN
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1,NaN
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1,NaN
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5,NaN
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1,NaN
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7,NaN
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7,NaN
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5,NaN
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9,NaN
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5,wrong item
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0,wrong item
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4,NaN
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0,NaN
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1,NaN
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8,NaN
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6,NaN
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9,bad quality
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6,NaN
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8,NaN
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2,NaN
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5,wrong item
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0,NaN
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1,NaN
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0,other

In [247]:
df_returns = pd.read_csv('returns.csv')

In [253]:
df_returns

  return_order_id return_reason
0  CA-2018-105893   bad quality
1  CA-2018-143336    wrong item
2  CA-2018-146703    wrong item
3  CA-2018-167164         other
4  CA-2019-106320   bad quality
5  CA-2019-115742         other
6  CA-2020-101343   bad quality
7  CA-2020-117590    wrong item

In [272]:
# This is used when two table have different columns 
df = pd.merge(left = df_orders , right = df_returns , left_on = 'order_id' , right_on = 'return_order_id',how = 'left')

In [255]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,return_order_id,return_reason
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9,NaN,NaN
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6,NaN,NaN
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9,NaN,NaN
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0,NaN,NaN
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5,NaN,NaN
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2,NaN,NaN
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0,NaN,NaN
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7,NaN,NaN
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8,NaN,NaN
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5,NaN,NaN
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3,NaN,NaN
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4,NaN,NaN
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4,NaN,NaN
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6,NaN,NaN
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9,NaN,NaN
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8,NaN,NaN
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3,CA-2018-105893,bad quality
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0,CA-2018-167164,other
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5,CA-2018-143336,wrong item
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0,CA-2018-143336,wrong item
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4,CA-2018-143336,wrong item
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1,NaN,NaN
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7,NaN,NaN
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0,NaN,NaN
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3,CA-2019-106320,bad quality
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2,NaN,NaN
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8,NaN,NaN
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1,NaN,NaN
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1,NaN,NaN
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5,NaN,NaN
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1,NaN,NaN
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7,NaN,NaN
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7,NaN,NaN
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5,NaN,NaN
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9,NaN,NaN
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5,CA-2020-117590,wrong item
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0,CA-2020-117590,wrong item
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4,NaN,NaN
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0,NaN,NaN
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1,NaN,NaN
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8,NaN,NaN
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6,NaN,NaN
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9,CA-2020-101343,bad quality
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6,NaN,NaN
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8,NaN,NaN
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2,NaN,NaN
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5,CA-2018-146703,wrong item
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0,NaN,NaN
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1,NaN,NaN
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0,CA-2019-115742,other

**Combining the data frames(Union All)**

In [259]:
emp1 = {"id":[1,2,3],
"name" : ["Ankit", "Sumit", "Amit"],
"salary" : [100,200,300]
}
emp2 = {"id" : [4,5,6],
"name" : ["Nachiket", "Rahul", "Vinay"],
"salary" : [400,500,600]
}

df1 = pd.DataFrame(emp1)
df2 = pd.DataFrame(emp2)

In [260]:
df1

   id   name  salary
0   1  Ankit     100
1   2  Sumit     200
2   3   Amit     300

In [261]:
df2

   id      name  salary
0   4  Nachiket     400
1   5     Rahul     500
2   6     Vinay     600

In [262]:
df = pd.concat([df1,df2])

In [263]:
df

   id      name  salary
0   1     Ankit     100
1   2     Sumit     200
2   3      Amit     300
0   4  Nachiket     400
1   5     Rahul     500
2   6     Vinay     600

In [267]:
df = pd.concat([df1,df2],ignore_index = True)

In [268]:
df

   id      name  salary
0   1     Ankit     100
1   2     Sumit     200
2   3      Amit     300
3   4  Nachiket     400
4   5     Rahul     500
5   6     Vinay     600

In [271]:
df_orders = pd.read_csv('orders.csv')
df_returns = pd.read_csv('returns.csv')

In [270]:
df

   id      name  salary
0   1     Ankit     100
1   2     Sumit     200
2   3      Amit     300
3   4  Nachiket     400
4   5     Rahul     500
5   6     Vinay     600

In [273]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,return_order_id,return_reason
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9,NaN,NaN
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6,NaN,NaN
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9,NaN,NaN
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0,NaN,NaN
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5,NaN,NaN
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2,NaN,NaN
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0,NaN,NaN
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7,NaN,NaN
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8,NaN,NaN
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5,NaN,NaN
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3,NaN,NaN
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4,NaN,NaN
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4,NaN,NaN
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6,NaN,NaN
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9,NaN,NaN
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8,NaN,NaN
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3,CA-2018-105893,bad quality
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0,CA-2018-167164,other
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5,CA-2018-143336,wrong item
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0,CA-2018-143336,wrong item
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4,CA-2018-143336,wrong item
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1,NaN,NaN
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7,NaN,NaN
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0,NaN,NaN
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3,CA-2019-106320,bad quality
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2,NaN,NaN
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8,NaN,NaN
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1,NaN,NaN
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1,NaN,NaN
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5,NaN,NaN
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1,NaN,NaN
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7,NaN,NaN
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7,NaN,NaN
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5,NaN,NaN
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9,NaN,NaN
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5,CA-2020-117590,wrong item
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0,CA-2020-117590,wrong item
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4,NaN,NaN
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0,NaN,NaN
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1,NaN,NaN
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8,NaN,NaN
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6,NaN,NaN
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9,CA-2020-101343,bad quality
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6,NaN,NaN
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8,NaN,NaN
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2,NaN,NaN
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5,CA-2018-146703,wrong item
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0,NaN,NaN
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1,NaN,NaN
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0,CA-2019-115742,other

In [274]:
df.to_csv("full_orders.csv") # by this a new csv file is built in the folder

In [275]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,return_order_id,return_reason
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9,NaN,NaN
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6,NaN,NaN
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9,NaN,NaN
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0,NaN,NaN
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5,NaN,NaN
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2,NaN,NaN
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0,NaN,NaN
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7,NaN,NaN
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8,NaN,NaN
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5,NaN,NaN
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3,NaN,NaN
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4,NaN,NaN
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4,NaN,NaN
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6,NaN,NaN
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9,NaN,NaN
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8,NaN,NaN
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3,CA-2018-105893,bad quality
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0,CA-2018-167164,other
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5,CA-2018-143336,wrong item
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0,CA-2018-143336,wrong item
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4,CA-2018-143336,wrong item
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1,NaN,NaN
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7,NaN,NaN
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0,NaN,NaN
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3,CA-2019-106320,bad quality
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2,NaN,NaN
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8,NaN,NaN
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1,NaN,NaN
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1,NaN,NaN
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5,NaN,NaN
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1,NaN,NaN
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7,NaN,NaN
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7,NaN,NaN
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5,NaN,NaN
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9,NaN,NaN
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5,CA-2020-117590,wrong item
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0,CA-2020-117590,wrong item
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4,NaN,NaN
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0,NaN,NaN
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1,NaN,NaN
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8,NaN,NaN
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6,NaN,NaN
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9,CA-2020-101343,bad quality
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6,NaN,NaN
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8,NaN,NaN
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2,NaN,NaN
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5,CA-2018-146703,wrong item
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0,NaN,NaN
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1,NaN,NaN
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0,CA-2019-115742,other

In [276]:
df.to_csv("full_orders.csv" , index = False) # by this 0 to n indexes are deleted from the new csv file

**Excel_file**

In [277]:
df.to_excel("full_orders.xlsx" , index = False)