In [1]:
import numpy as np
import pandas as pd

# DataFrames

**Creating a DataFrame**

In [17]:
# By Dictionary
  
data = {
    'Name': ['John','Anna','Peter','Linda'],
    'Age':[28,34,29,42],
    'City':['New York','Paris','Berlin','London'],
    'Salary':[65000,70000,62000,85000]
}
df = pd.DataFrame(data)

In [3]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [38]:
# By List

data_list = [
    ['John',28,'New York',65000],
    ['Anna',34,'Paris',70000],
    ['Peter',29,'Berlin',62000],
    ['Linda',42,'London',85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns=columns)

In [39]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

**Selection and indexing of Columns**

In [19]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [23]:
df2[['Name','City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [ ]:
df2[]

**Creating a new Column**

In [24]:
df2["Designation"] = ["Doctor","Engineer","Lawyer","CA"]

In [25]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Lawyer
3  Linda   42    London   85000          CA

**Removing Columns**

In [29]:
df2.drop("Designation",axis=1,inplace=True)

In [40]:
# Multiple Removing Columns

df2.drop(["City","Salary"],axis=1)

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

**Selecting Rows**

In [42]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [45]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [46]:
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

**Selecting Subsets of Rows and Columns**

In [47]:
df.loc[[0,1]] [["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

**Conditional Selection**

In [48]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [50]:
# I only want to see those people whose age is above 30.

df2[df2["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [54]:
# I only want People whose age is above than 30 and their city must be Paris

df2[(df2["Age"] > 30) & (df2["City"] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000