In [4]:
pip install pandas

Requirement already satisfied: pandas in c:\users\dharm\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dharm\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dharm\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dharm\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dharm\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\dharm\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [7]:
import numpy as np
import pandas as pd

**Merging 2 dataframes**

In [14]:
# DataFrame 1 : employees information
employees = pd.DataFrame({
    'employee_id':[1,2,3,4,5],
    'name':['John','Anna','Peter','Linda','Bob'],
    'department':['HR','IT','Finance','IT','HR']
})

# DataFrame 2 : Salary information
salaries = pd.DataFrame({
    'employee_id' : [1,2,3,6,7],
    'salary' : [60000,80000,65000,70000,90000],
    'bonus' : [5000,10000,7000,8000,12000]
})

In [11]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [15]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [18]:
pd.merge(employees,salaries,on='employee_id',how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [19]:
pd.merge(employees,salaries,on='employee_id',how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [20]:
pd.merge(employees,salaries,on='employee_id',how='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [21]:
pd.merge(employees,salaries,on='employee_id',how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

**Concatenation of 2 dataframes**

In [24]:
# DataFrame 1
df1 = pd.DataFrame({
    'A' : ['A0','A1','A2'],
    'B' : ['B0','B1','B2'],
    'C' : ['C0','C1','C2']
})

# DataFrame 2
df2 = pd.DataFrame({
    'A': ['A3','A4','A5'],
    'B': ['B3','B4','B5'],
    'C': ['C3','C4','C5']
    
})

In [25]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [26]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [27]:
pd.concat([df1,df2]) # it takes two names within list

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [28]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

**Joining of 2 dataframes**

In [32]:
# DataFrame 1

df1 = pd.DataFrame({
    'name': ['Alice','Bob','Charlie']
},index=[1,2,3])

# DataFrame 2
df2 = pd.DataFrame({
    'Score': [85,90,75]
},index=[2,3,4])

In [34]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [35]:
df2

   Score
2     85
3     90
4     75

In [37]:
df1.join(df2,how='outer')

      name  Score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [38]:
df2.join(df1)

   Score     name
2     85      Bob
3     90  Charlie
4     75      NaN